version: '3.4'

services:
  jhipster-kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://jhipster-elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://jhipster-elasticsearch:9200"]'
